FROM rockylinux:9.2


RUN dnf -y install git python3 httpd python3-pip && \
    pip3 install virtualenv gunicorn

RUN useradd webtool && echo "webtool:webtool" | chpasswd
USER webtool
WORKDIR /home/webtool
RUN git clone https://github.com/nfourniol/whereismyvm.git 
WORKDIR /home/webtool/whereismyvm
RUN python3 -m venv venv
RUN source ./venv/bin/activate
RUN pip3 install -r requirements.txt
RUN gunicorn whereismyvm.wsgi --bind 127.0.0.1:8888 --daemon
    
COPY ./whereismyvm.conf /etc/httpd/conf.d/
COPY ./config.yaml /home/webtool/whereismyvm/config.yaml
COPY ./hypervisor.yaml /home/webtool/whereismyvm/hypervisor.yaml

USER root
EXPOSE 80
ENTRYPOINT ["/usr/sbin/httpd", "-D", "FOREGROUND"]
# docker image build -t whereismyvm:v1.0 .
# docker run --name whereismyvm -p 7777:80 whereismyvm:v1.0